# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bf4e00430a603c0f0199580a17fcd785b7e09443d22b33a4a3ccadc856e3bb2f45553a19d75fc4dada2211cb2cfe68dd63f466dcd4c93fafbd6b43c5c4b4762

test:
  secret_key_base: 9bcb3c1ce55b96647ea0b8173306d0101a88ac92922fda29d55ecf1593ba5f6ec084565ae253dc781e757f130c52b99eaeaee1a8003c28ca4133d42ded135878

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
